import type { Product, ProductCategory } from "@/types";

const wikiImage = (fileName: string, width = 1200) =>
  `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(fileName)}?width=${width}`;

export const categories: { name: ProductCategory; description: string }[] = [
  { name: "iPhones", description: "iPhones revisados, com estado claro e garantia informada." },
  { name: "Androids", description: "Modelos populares, procurados e com manutenção mais acessível." },
  { name: "MacBooks", description: "MacBooks selecionados para estudo, trabalho e criação." },
  { name: "Notebooks", description: "Notebooks Windows para rotina, home office e faculdade." },
  { name: "PCs", description: "Computadores prontos para uso, upgrade ou setup gamer leve." },
  { name: "Acessorios", description: "Carregadores, capas, fones, suportes e itens para setup." },
  { name: "Promocoes", description: "Oportunidades com preço especial e disponibilidade limitada." }
];

export const products: Product[] = [
  {
    id: "iphone-13-128-meia-noite",
    name: "iPhone 13 128GB Meia-noite",
    brand: "Apple",
    model: "iPhone 13",
    category: "iPhones",
    condition: "Seminovo",
    conservation: "Muito bom, pequenas marcas laterais",
    price: 2890,
    oldPrice: 3190,
    images: [wikiImage("IPhone 13.jpg"), wikiImage("IPhone 11.jpeg")],
    description: "iPhone revisado, desbloqueado, com ótima performance para uso diário, fotos, redes sociais e trabalho.",
    specs: ["Tela Super Retina XDR 6,1 pol", "Chip A15 Bionic", "128GB", "Face ID", "5G"],
    warranty: "90 dias de garantia da loja",
    availability: "Disponivel",
    storage: "128GB",
    color: "Meia-noite",
    batteryHealth: "88%",
    includedAccessories: ["Cabo USB-C para Lightning", "Película instalada"],
    revised: true,
    notes: ["Sem bloqueios", "Câmeras testadas", "Não acompanha caixa original"],
    featured: true,
    badge: "Mais procurado"
  },
  {
    id: "galaxy-a55-256-azul",
    name: "Galaxy A55 5G 256GB Azul",
    brand: "Samsung",
    model: "Galaxy A55",
    category: "Androids",
    condition: "Seminovo",
    conservation: "Excelente, tela sem riscos aparentes",
    price: 1890,
    images: [wikiImage("Samsung Galaxy A54 5G 2023.jpg"), wikiImage("GalaxyS21.png")],
    description: "Android popular premium, com bom desempenho, bateria forte e manutenção com peças fáceis de encontrar.",
    specs: ["Tela Super AMOLED 6,6 pol", "256GB", "8GB RAM", "5G", "Câmera tripla"],
    warranty: "90 dias de garantia da loja",
    availability: "Disponivel",
    storage: "256GB",
    color: "Azul",
    batteryHealth: "Bateria testada com boa autonomia",
    includedAccessories: ["Cabo USB-C", "Capa transparente"],
    revised: true,
    notes: ["Aparelho nacional", "Leitor biométrico funcionando", "Pode haver micro marcas de uso"],
    featured: true
  },
  {
    id: "macbook-air-m1-256-prata",
    name: "MacBook Air M1 256GB Prata",
    brand: "Apple",
    model: "MacBook Air M1",
    category: "MacBooks",
    condition: "Usado",
    conservation: "Bom, pequenas marcas na tampa",
    price: 4290,
    oldPrice: 4590,
    images: [wikiImage("MacBook Air .jpg"), wikiImage("Lenovo_IdeaPad_320.jpg")],
    description: "MacBook leve, silencioso e muito eficiente para estudos, programação, edição leve e trabalho remoto.",
    specs: ["Chip Apple M1", "8GB RAM", "SSD 256GB", "Tela Retina 13 pol", "macOS atualizado"],
    warranty: "60 dias de garantia da loja",
    availability: "Disponivel",
    storage: "256GB SSD",
    color: "Prata",
    batteryHealth: "Ciclos dentro do esperado",
    includedAccessories: ["Fonte original", "Cabo USB-C"],
    revised: true,
    notes: ["Teclado testado", "Carregamento normal", "Ideal para produtividade"],
    featured: true,
    badge: "Oferta"
  },
  {
    id: "notebook-dell-inspiron-i5",
    name: "Dell Inspiron i5 16GB SSD",
    brand: "Dell",
    model: "Inspiron",
    category: "Notebooks",
    condition: "Seminovo",
    conservation: "Muito bom, carcaça preservada",
    price: 2490,
    images: [wikiImage("Lenovo_IdeaPad_320.jpg"), wikiImage("Samsung NC110-7486.jpg")],
    description: "Notebook Windows revisado, pronto para trabalho, estudos, chamadas e navegação pesada.",
    specs: ["Intel Core i5", "16GB RAM", "SSD 512GB", "Windows 11", "Tela 15,6 pol"],
    warranty: "90 dias de garantia da loja",
    availability: "Disponivel",
    storage: "512GB SSD",
    color: "Cinza",
    includedAccessories: ["Fonte Dell"],
    revised: true,
    notes: ["Sistema formatado", "Limpeza preventiva feita", "Bateria com autonomia regular"],
    featured: true
  },
  {
    id: "pc-setup-ryzen",
    name: "PC Ryzen 5 com SSD e monitor",
    brand: "Setup montado",
    model: "Ryzen 5",
    category: "PCs",
    condition: "Usado",
    conservation: "Bom, gabinete com marcas discretas",
    price: 2190,
    images: [wikiImage("Lenovo IdeaPad U300s 20110530.jpg"), wikiImage("Samsung NC110-7486.jpg")],
    description: "Computador revisado para estudo, escritório, multitarefa e games leves com possibilidade de upgrade.",
    specs: ["Ryzen 5", "16GB RAM", "SSD 480GB", "Monitor incluso", "Windows 11"],
    warranty: "60 dias de garantia da loja",
    availability: "Disponivel",
    storage: "480GB SSD",
    color: "Preto",
    includedAccessories: ["Monitor", "Cabo de força", "Teclado básico"],
    revised: true,
    notes: ["Limpeza interna feita", "Temperaturas testadas", "Pode receber upgrade de placa de vídeo"],
    featured: false
  },
  {
    id: "kit-acessorios-usbc",
    name: "Kit USB-C Essencial",
    brand: "Tech Select",
    model: "USB-C",
    category: "Acessorios",
    condition: "Novo",
    conservation: "Lacrado",
    price: 149,
    images: [wikiImage("Apple USB-C (USB Type C) 87W Power Adapter for MacBook Pro (48979218053).jpg")],
    description: "Kit com carregador, cabo reforçado e adaptador para deixar o aparelho pronto para rotina.",
    specs: ["Carregador USB-C", "Cabo 1m", "Adaptador compacto", "Compatível com celulares populares"],
    warranty: "30 dias de garantia",
    availability: "Disponivel",
    color: "Branco",
    includedAccessories: ["Carregador", "Cabo", "Adaptador"],
    revised: false,
    notes: ["Produto novo", "Consulte compatibilidade antes da compra"],
    featured: false
  },
  {
    id: "moto-g54-128-preto",
    name: "Moto G54 128GB Preto",
    brand: "Motorola",
    model: "Moto G54",
    category: "Androids",
    condition: "Seminovo",
    conservation: "Muito bom, sinais leves de uso",
    price: 890,
    images: [wikiImage("Motorola phones store.jpg"), wikiImage("Redmi Note 9.jpg")],
    description: "Android popular com boa procura, ideal para quem quer custo-benefício e manutenção simples.",
    specs: ["128GB", "4GB RAM", "Tela 6,5 pol", "Bateria 5000mAh", "5G"],
    warranty: "60 dias de garantia da loja",
    availability: "Disponivel",
    storage: "128GB",
    color: "Preto",
    batteryHealth: "Bateria testada",
    includedAccessories: ["Cabo USB-C"],
    revised: true,
    notes: ["Aparelho desbloqueado", "Pronto para uso"],
    featured: false
  },
  {
    id: "redmi-note-13-256",
    name: "Redmi Note 13 256GB",
    brand: "Xiaomi",
    model: "Redmi Note 13",
    category: "Promocoes",
    condition: "Seminovo",
    conservation: "Excelente",
    price: 1190,
    oldPrice: 1350,
    images: [wikiImage("Redmi Note 9.jpg"), wikiImage("Samsung Galaxy A54 5G 2023.jpg")],
    description: "Aparelho com tela grande, bom armazenamento e preço especial para venda rápida.",
    specs: ["256GB", "8GB RAM", "AMOLED", "Câmera 108MP", "Carregamento rápido"],
    warranty: "60 dias de garantia da loja",
    availability: "Reservado",
    storage: "256GB",
    color: "Preto",
    batteryHealth: "Bateria testada",
    includedAccessories: ["Cabo USB-C", "Capa"],
    revised: true,
    notes: ["Produto reservado por tempo limitado", "Consulte disponibilidade no WhatsApp"],
    featured: false,
    badge: "Promo"
  }
];

export function getProductById(id: string) {
  return products.find((product) => product.id === id);
}

export function getProductsByCategory(category?: string) {
  if (!category || category === "Todos") return products;
  return products.filter((product) => product.category === category);
}
